### ISSUE TITLE
Couldnt build from aur hws-git

### ISSUE THREAD

**Issue by micwoj92** [StreakyCobra/hws#2]
as you also maintain that package, I will drop that here:

ocamlbuild -classic-display "src"/main.native
ocamlbuild -classic-display "tests"/tests.native
cd "man"; make all
hws.odocl: Generation
make[1]: Entering directory '/home/micwoj92/.cache/pikaur/build/hws-git/src/hws/man'
hws.odocl: Generated
ocamlbuild -classic-display src/commands/cmd_status.cma
a2x --doctype manpage --format manpage --asciidoc-opts="-f asciidoc.conf -a hws_version=0.1.0" hws.1.adoc
/bin/bash: a2x: command not found
/bin/bash: ocamlbuild: command not found
/bin/bash: ocamlbuild: command not found
/bin/bash: ocamlbuild: command not found
make[1]: *** [Makefile:28: hws.1] Error 127
make[1]: Leaving directory '/home/micwoj92/.cache/pikaur/build/hws-git/src/hws/man'
make: *** [Makefile:148: src/commands/cmd_status.cma] Error 127
make: *** Waiting for unfinished jobs....
make: *** [Makefile:152: "tests"/tests.native] Error 127
make: *** [Makefile:152: "src"/main.native] Error 127
make: *** [Makefile:68: man] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by StreakyCobra** [comment]
Hi, this project was never really working and is not maintained anymore. It was planned to be a replacement of https://github.com/StreakyCobra/gws but that never happened. The current maintainer of `gws` has started to work on a port in Rust if of interest to you: https://github.com/emlun/gws2 :)

**Comment by micwoj92** [comment]
Oh, can I submit request to remove this package from AUR then?

**Comment by StreakyCobra** [comment]
Yes sure :)
